/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as StudioRouteImport } from './routes/studio'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as LendRouteImport } from './routes/lend'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AppRouteImport } from './routes/app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppIndexRouteImport } from './routes/app.index'
import { Route as VSlugRouteImport } from './routes/v.$slug'
import { Route as CheckoutReturnRouteImport } from './routes/checkout.return'
import { Route as AppWriteRouteImport } from './routes/app.write'
import { Route as AppStewardRouteImport } from './routes/app.steward'
import { Route as AppSetupRouteImport } from './routes/app.setup'
import { Route as ApiPublicPaymentsWebhookRouteImport } from './routes/api/public/payments/webhook'

const StudioRoute = StudioRouteImport.update({
  id: '/studio',
  path: '/studio',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const LendRoute = LendRouteImport.update({
  id: '/lend',
  path: '/lend',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const VSlugRoute = VSlugRouteImport.update({
  id: '/v/$slug',
  path: '/v/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutReturnRoute = CheckoutReturnRouteImport.update({
  id: '/checkout/return',
  path: '/checkout/return',
  getParentRoute: () => rootRouteImport,
} as any)
const AppWriteRoute = AppWriteRouteImport.update({
  id: '/write',
  path: '/write',
  getParentRoute: () => AppRoute,
} as any)
const AppStewardRoute = AppStewardRouteImport.update({
  id: '/steward',
  path: '/steward',
  getParentRoute: () => AppRoute,
} as any)
const AppSetupRoute = AppSetupRouteImport.update({
  id: '/setup',
  path: '/setup',
  getParentRoute: () => AppRoute,
} as any)
const ApiPublicPaymentsWebhookRoute =
  ApiPublicPaymentsWebhookRouteImport.update({
    id: '/api/public/payments/webhook',
    path: '/api/public/payments/webhook',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/auth': typeof AuthRoute
  '/dashboard': typeof DashboardRoute
  '/lend': typeof LendRoute
  '/onboarding': typeof OnboardingRoute
  '/pricing': typeof PricingRoute
  '/studio': typeof StudioRoute
  '/app/setup': typeof AppSetupRoute
  '/app/steward': typeof AppStewardRoute
  '/app/write': typeof AppWriteRoute
  '/checkout/return': typeof CheckoutReturnRoute
  '/v/$slug': typeof VSlugRoute
  '/app/': typeof AppIndexRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/dashboard': typeof DashboardRoute
  '/lend': typeof LendRoute
  '/onboarding': typeof OnboardingRoute
  '/pricing': typeof PricingRoute
  '/studio': typeof StudioRoute
  '/app/setup': typeof AppSetupRoute
  '/app/steward': typeof AppStewardRoute
  '/app/write': typeof AppWriteRoute
  '/checkout/return': typeof CheckoutReturnRoute
  '/v/$slug': typeof VSlugRoute
  '/app': typeof AppIndexRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/auth': typeof AuthRoute
  '/dashboard': typeof DashboardRoute
  '/lend': typeof LendRoute
  '/onboarding': typeof OnboardingRoute
  '/pricing': typeof PricingRoute
  '/studio': typeof StudioRoute
  '/app/setup': typeof AppSetupRoute
  '/app/steward': typeof AppStewardRoute
  '/app/write': typeof AppWriteRoute
  '/checkout/return': typeof CheckoutReturnRoute
  '/v/$slug': typeof VSlugRoute
  '/app/': typeof AppIndexRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/auth'
    | '/dashboard'
    | '/lend'
    | '/onboarding'
    | '/pricing'
    | '/studio'
    | '/app/setup'
    | '/app/steward'
    | '/app/write'
    | '/checkout/return'
    | '/v/$slug'
    | '/app/'
    | '/api/public/payments/webhook'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/dashboard'
    | '/lend'
    | '/onboarding'
    | '/pricing'
    | '/studio'
    | '/app/setup'
    | '/app/steward'
    | '/app/write'
    | '/checkout/return'
    | '/v/$slug'
    | '/app'
    | '/api/public/payments/webhook'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/auth'
    | '/dashboard'
    | '/lend'
    | '/onboarding'
    | '/pricing'
    | '/studio'
    | '/app/setup'
    | '/app/steward'
    | '/app/write'
    | '/checkout/return'
    | '/v/$slug'
    | '/app/'
    | '/api/public/payments/webhook'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  AuthRoute: typeof AuthRoute
  DashboardRoute: typeof DashboardRoute
  LendRoute: typeof LendRoute
  OnboardingRoute: typeof OnboardingRoute
  PricingRoute: typeof PricingRoute
  StudioRoute: typeof StudioRoute
  CheckoutReturnRoute: typeof CheckoutReturnRoute
  VSlugRoute: typeof VSlugRoute
  ApiPublicPaymentsWebhookRoute: typeof ApiPublicPaymentsWebhookRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/studio': {
      id: '/studio'
      path: '/studio'
      fullPath: '/studio'
      preLoaderRoute: typeof StudioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lend': {
      id: '/lend'
      path: '/lend'
      fullPath: '/lend'
      preLoaderRoute: typeof LendRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/v/$slug': {
      id: '/v/$slug'
      path: '/v/$slug'
      fullPath: '/v/$slug'
      preLoaderRoute: typeof VSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout/return': {
      id: '/checkout/return'
      path: '/checkout/return'
      fullPath: '/checkout/return'
      preLoaderRoute: typeof CheckoutReturnRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/write': {
      id: '/app/write'
      path: '/write'
      fullPath: '/app/write'
      preLoaderRoute: typeof AppWriteRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/steward': {
      id: '/app/steward'
      path: '/steward'
      fullPath: '/app/steward'
      preLoaderRoute: typeof AppStewardRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/setup': {
      id: '/app/setup'
      path: '/setup'
      fullPath: '/app/setup'
      preLoaderRoute: typeof AppSetupRouteImport
      parentRoute: typeof AppRoute
    }
    '/api/public/payments/webhook': {
      id: '/api/public/payments/webhook'
      path: '/api/public/payments/webhook'
      fullPath: '/api/public/payments/webhook'
      preLoaderRoute: typeof ApiPublicPaymentsWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AppRouteChildren {
  AppSetupRoute: typeof AppSetupRoute
  AppStewardRoute: typeof AppStewardRoute
  AppWriteRoute: typeof AppWriteRoute
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppSetupRoute: AppSetupRoute,
  AppStewardRoute: AppStewardRoute,
  AppWriteRoute: AppWriteRoute,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  AuthRoute: AuthRoute,
  DashboardRoute: DashboardRoute,
  LendRoute: LendRoute,
  OnboardingRoute: OnboardingRoute,
  PricingRoute: PricingRoute,
  StudioRoute: StudioRoute,
  CheckoutReturnRoute: CheckoutReturnRoute,
  VSlugRoute: VSlugRoute,
  ApiPublicPaymentsWebhookRoute: ApiPublicPaymentsWebhookRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
